spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: shop1
    password: shop1pass
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
